### ISSUE TITLE
GeoSpace visualization incompatible with Mesa ≥ 3.3 (SolaraViz API change)

### ISSUE THREAD

**Issue by wang-boyu** [mesa/mesa-geo#295]
**Describe the bug**

GeoSpace visualization in Mesa-Geo currently breaks when used with Mesa 3.3 / 3.4, due to upstream changes in Mesa’s SolaraViz visualization API.

Error when using `make_geospace_component` with SolaraViz:

```bash
Traceback (most recent call last):
  File "/Users/boyu/GitHubProjects/mesa-examples/venv/lib/python3.14/site-packages/reacton/core.py", line 1702, in _render
    root_element = el.component.f(*el.args, **el.kwargs)
  File "/Users/boyu/GitHubProjects/mesa-examples/venv/lib/python3.14/site-packages/mesa/mesa_logging.py", line 132, in wrapper
    res = func(*args, **kwargs)
  File "/Users/boyu/GitHubProjects/mesa-examples/venv/lib/python3.14/site-packages/mesa/visualization/solara_viz.py", line 151, in SolaraViz
    display_components.insert(0, (create_space_component(renderer.value), 0))
                                                         ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'value'
```

**Current workaround**

Pin Mesa to <3.3 to keep GeoSpace visualization working: https://github.com/mesa/mesa-geo/pull/294

**Goal**

Update Mesa-Geo’s GeoSpace visualization integration to work with Mesa ≥ 3.3 (latest SolaraViz), so the dependency pin can be removed.

**References**
- [Frontend Upgrade - Project MESA](https://gist.github.com/Sahil-Chhoker/470d78683664dffc05725bd858beb494)
- https://github.com/mesa/mesa/pull/2893
